ㅍreplicaCount: 1

auth:
  enabled: false

externalAccess:
  enabled: false

listeners:
  client:
    protocol: PLAINTEXT

serviceAccount:
  create: true
  name: ""

#####################################
# (1) Kafka 브로커 공통 설정 덮어쓰기
#####################################
overrideConfiguration: |
  broker.id=0
  listeners=PLAINTEXT://0.0.0.0:9092
  advertised.listeners=PLAINTEXT://localhost:9092
  listener.security.protocol.map=PLAINTEXT:PLAINTEXT
  num.network.threads=3
  num.io.threads=8
  socket.send.buffer.bytes=102400
  socket.receive.buffer.bytes=102400
  socket.request.max.bytes=104857600
  log.dirs=/tmp/kafka-logs
  num.partitions=1
  offsets.topic.replication.factor=1
  transaction.state.log.replication.factor=1
  transaction.state.log.min.isr=1
  log.retention.hours=168
  log.retention.check.interval.ms=300000
  zookeeper.connect=zookeeper:2181
  zookeeper.connection.timeout.ms=18000
  group.initial.rebalance.delay.ms=0

#####################################
# (2) Zookeeper 설정
#####################################
zookeeper:
  enabled: true
  replicaCount: 1
  auth:
    enabled: false
  overrideConfiguration: |
    dataDir=/tmp/zookeeper
    clientPort=2181
    maxClientCnxns=0
    admin.enableServer=false
